vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
       recipe_images:
           uri_prefix: /Img
           upload_destination: '%kernel.project_dir%/public/Img'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
