vich_uploader:
    db_driver: orm

    mappings:
       recipe_images:
           uri_prefix: /Img/products
           upload_destination: '%kernel.project_dir%/public/Img/'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
